# Generated by Django 3.2.16 on 2022-11-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_address_line_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_address_line_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_postcode',
        ),
    ]
