# Generated by Django 3.2.16 on 2022-12-05 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221128_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_address_line_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_address_line_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_postcode',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
    ]
