# Generated by Django 4.1.4 on 2022-12-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='wish_item',
        ),
    ]
