# Generated by Django 4.0 on 2022-12-11 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_product_wishlist_wish_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wish_item',
            new_name='product',
        ),
    ]
