# Generated by Django 4.0 on 2023-01-31 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_remove_order_customer_alter_order_address_line_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
