# Generated by Django 3.2.16 on 2022-11-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
