# Generated by Django 3.2.16 on 2022-11-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
