# Generated by Django 4.0 on 2023-02-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_name_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
