# Generated by Django 4.0 on 2023-02-02 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
