# Generated by Django 4.0 on 2023-04-26 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_userreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
